name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3 
      - name: Select xcodeproj
        run: sudo xcode-select -switch /Applications/Xcode_15.0.app     
      - name: Xcode build and test for macOS
        run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Xcode build and test for iOS
        run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_iOS" -destination 'platform=iOS Simulator,name=iPhone 14' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
